using Typewriter.Abstractions;
using Typewriter.Engine;
using Xunit;

namespace Typewriter.Engine.Tests;

public sealed class ExternalRecipeCompatibilityTests
{
    [Fact]
    public void RenderSupportsAngularSystemTextJsonServiceRecipe()
    {
        var recipePath = ResolveExternalRecipePath(
            "Angular",
            "System.Text.Json",
            "services",
            "_AutogeneratedServices.tst");
        if (!File.Exists(path: recipePath))
        {
            return;
        }

#pragma warning disable SEC0116
        var templateContent = File.ReadAllText(path: recipePath);
#pragma warning restore SEC0116
        var metadata = CreateAngularWebApiMetadata();
        var diagnostics = new List<GenerationDiagnostic>();
        var renderer = new TemplateRenderer(typeMapper: new TypeScriptTypeMapper());
        var document = TemplateDocument.Parse(template: new TemplateFile(Path: recipePath, Content: templateContent), diagnostics: diagnostics);

        var output = renderer.Render(template: document, metadata: metadata, diagnostics: diagnostics);

        diagnostics.Should().NotContain(diagnostic => diagnostic.Severity != DiagnosticSeverity.Info);
        output.Should().Contain("import { UserDto } from '../models/UserDto';");
        output.Should().Contain("import { CreateUserRequest } from '../models/CreateUserRequest';");
        output.Should().Contain("export interface IApiUsersService");
        output.Should().Contain("export class ApiUsersService implements IApiUsersService");
        output.Should().Contain("getItemAsyncnumberstring(id: number, search: string)");
        output.Should().NotContain("getItemAsyncnumberstring | null");
        output.Should().Contain("this.usersServiceUrl");
        output.Should().Contain("items/{id}");
        output.Should().Contain("items");
        output.Should().Contain("request,");
    }

    [Fact]
    public void RenderSupportsAngularSystemTextJsonModelRecipeDefaults()
    {
        var recipePath = ResolveExternalRecipePath(
            "src",
            "AngularWebApiSample",
            "ClientApp",
            "apps",
            "client-app",
            "src",
            "api",
            "models",
            "_AutogeneratedModels.tst");
        if (!File.Exists(path: recipePath))
        {
            return;
        }

#pragma warning disable SEC0116
        var templateContent = File.ReadAllText(path: recipePath);
#pragma warning restore SEC0116
        var metadata = CreateAngularWebApiModelMetadata();
        var diagnostics = new List<GenerationDiagnostic>();
        var renderer = new TemplateRenderer(typeMapper: new TypeScriptTypeMapper());
        var document = TemplateDocument.Parse(template: new TemplateFile(Path: recipePath, Content: templateContent), diagnostics: diagnostics);

        var output = renderer.Render(template: document, metadata: metadata, diagnostics: diagnostics);

        diagnostics.Should().NotContain(diagnostic => diagnostic.Severity != DiagnosticSeverity.Info);
        output.Should().Contain("import { SimpleModel } from './SimpleModel';");
        output.Should().Contain("middleName?: string | null;");
        output.Should().Contain("this.id = initObj.id || 0;");
        output.Should().Contain("this.simpleModels = initObj.simpleModels || [];");
        output.Should().Contain("this.firstName = initObj.firstName || '';");
        output.Should().Contain("this.middleName = initObj.middleName || null;");
        output.Should().Contain("this.lastName = initObj.lastName || '';");
        output.Should().Contain("this.firstSet = initObj.firstSet || FirstSet.ValA;");
        output.Should().Contain("this.secondSet = initObj.secondSet || SecondSet.ValA;");
    }

    [Fact]
    public void RenderSupportsAngularSystemTextJsonRuntimeSchemaRecipe()
    {
        var recipePath = ResolveExternalRecipePath(
            "Angular",
            "System.Text.Json",
            "models",
            "_AutogeneratedRuntimeSchemas.tst");
        if (!File.Exists(path: recipePath))
        {
            return;
        }

#pragma warning disable SEC0116
        var templateContent = File.ReadAllText(path: recipePath);
#pragma warning restore SEC0116
        var metadata = CreateAngularWebApiModelMetadata();
        var diagnostics = new List<GenerationDiagnostic>();
        var renderer = new TemplateRenderer(typeMapper: new TypeScriptTypeMapper());
        var document = TemplateDocument.Parse(
            template: new TemplateFile(Path: recipePath, Content: templateContent),
            diagnostics: diagnostics);

        var output = renderer.Render(template: document, metadata: metadata, diagnostics: diagnostics);

        diagnostics.Should().NotContain(diagnostic => diagnostic.Severity != DiagnosticSeverity.Info);
        output.Should().Contain("'firstSet': schema.property(schema.optional((schema.number() as RuntimeSchema<FirstSet>)))");
        output.Should().Contain("'secondSet': schema.property(schema.optional((schema.string() as RuntimeSchema<SecondSet>)))");
        output.Should().Contain("schema.array(schema.reference<SimpleModel>('AngularWebApiSample.Models.SimpleModel'))");
        output.Should().NotContain("$Properties");
    }

    private static string ResolveExternalRecipePath(params string[] relativeParts)
    {
        var repositoryRoot = FindRepositoryRoot();
        var gitHubRoot = Directory.GetParent(path: repositoryRoot)?.FullName ?? repositoryRoot;
        return Path.Combine(paths: [gitHubRoot, "NetCoreTypewriterRecipes", .. relativeParts]);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(path: AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(path: Path.Combine(path1: directory.FullName, path2: "AdaskoTheBeAsT.Typewriter.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        return AppContext.BaseDirectory;
    }

    private static ProjectMetadata CreateAngularWebApiMetadata()
    {
        const string ControllerFullName = "AngularWebApiSample.Controllers.UsersController";
        const string GetMethodFullName = "AngularWebApiSample.Controllers.UsersController.GetItemAsync(int, string)";
        const string PostMethodFullName = "AngularWebApiSample.Controllers.UsersController.CreateAsync(CreateUserRequest, CancellationToken)";
        var userDtoType = TypeReference(
            name: "UserDto",
            fullName: "AngularWebApiSample.Models.UserDto",
            isNullable: false,
            isPrimitive: false);
        var requestType = TypeReference(
            name: "CreateUserRequest",
            fullName: "AngularWebApiSample.Models.CreateUserRequest",
            isNullable: false,
            isPrimitive: false);
        var taskOfUserDtoType = TypeReference(
            name: "Task",
            fullName: "System.Threading.Tasks.Task",
            isNullable: false,
            isPrimitive: false,
            typeArguments: [userDtoType]);

        var controller = new TypeMetadata(
            Name: "UsersController",
            FullName: ControllerFullName,
            Namespace: "AngularWebApiSample.Controllers",
            Kind: TypeMetadataKind.Class,
            Accessibility: MetadataAccessibility.Public,
            Properties: [],
            Attributes:
            [
                new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.GenerateFrontendTypeAttribute", Arguments: []),
                new AttributeMetadata(Name: "Route", FullName: "Microsoft.AspNetCore.Mvc.RouteAttribute", Arguments: [new AttributeArgumentMetadata(Name: null, Value: "api/[controller]")]),
            ],
            BaseTypes: [TypeReference(name: "ControllerBase", fullName: "Microsoft.AspNetCore.Mvc.ControllerBase", isNullable: false, isPrimitive: false)],
            EnumValues: [],
            IsNullableAware: true)
        {
            Methods =
            [
                new MethodMetadata(
                    Name: "GetItemAsync",
                    FullName: GetMethodFullName,
                    ReturnType: taskOfUserDtoType,
                    Accessibility: MetadataAccessibility.Public,
                    IsStatic: false,
                    IsAbstract: false,
                    IsGeneric: false,
                    Parameters:
                    [
                        new ParameterMetadata(
                            Name: "id",
                            FullName: GetMethodFullName + ".id",
                            Type: TypeReference(name: "Int32", fullName: "System.Int32", isNullable: false),
                            HasDefaultValue: false,
                            DefaultValue: null,
                            Attributes: [new AttributeMetadata(Name: "FromRoute", FullName: "Microsoft.AspNetCore.Mvc.FromRouteAttribute", Arguments: [])],
                            ParentMethodFullName: GetMethodFullName),
                        new ParameterMetadata(
                            Name: "search",
                            FullName: GetMethodFullName + ".search",
                            Type: TypeReference(name: "String", fullName: "System.String", isNullable: true),
                            HasDefaultValue: true,
                            DefaultValue: "null",
                            Attributes: [],
                            ParentMethodFullName: GetMethodFullName),
                    ],
                    Attributes:
                    [
                        new AttributeMetadata(Name: "HttpGet", FullName: "Microsoft.AspNetCore.Mvc.HttpGetAttribute", Arguments: [new AttributeArgumentMetadata(Name: null, Value: "items/{id}")]),
                        new AttributeMetadata(Name: "ProducesResponseType", FullName: "Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute", Arguments: [new AttributeArgumentMetadata(Name: null, Value: "typeof(AngularWebApiSample.Models.UserDto), 200")]),
                    ],
                    ParentTypeFullName: ControllerFullName),
                new MethodMetadata(
                    Name: "CreateAsync",
                    FullName: PostMethodFullName,
                    ReturnType: taskOfUserDtoType,
                    Accessibility: MetadataAccessibility.Public,
                    IsStatic: false,
                    IsAbstract: false,
                    IsGeneric: false,
                    Parameters:
                    [
                        new ParameterMetadata(
                            Name: "request",
                            FullName: PostMethodFullName + ".request",
                            Type: requestType,
                            HasDefaultValue: false,
                            DefaultValue: null,
                            Attributes: [new AttributeMetadata(Name: "FromBody", FullName: "Microsoft.AspNetCore.Mvc.FromBodyAttribute", Arguments: [])],
                            ParentMethodFullName: PostMethodFullName),
                        new ParameterMetadata(
                            Name: "cancellationToken",
                            FullName: PostMethodFullName + ".cancellationToken",
                            Type: TypeReference(name: "CancellationToken", fullName: "System.Threading.CancellationToken", isNullable: false, isPrimitive: false),
                            HasDefaultValue: false,
                            DefaultValue: null,
                            Attributes: [],
                            ParentMethodFullName: PostMethodFullName),
                    ],
                    Attributes:
                    [
                        new AttributeMetadata(Name: "HttpPost", FullName: "Microsoft.AspNetCore.Mvc.HttpPostAttribute", Arguments: [new AttributeArgumentMetadata(Name: null, Value: "items")]),
                        new AttributeMetadata(Name: "ProducesResponseType", FullName: "Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute", Arguments: [new AttributeArgumentMetadata(Name: null, Value: "typeof(AngularWebApiSample.Models.UserDto), 201")]),
                    ],
                    ParentTypeFullName: ControllerFullName),
            ],
        };
        var userDto = new TypeMetadata(
            Name: "UserDto",
            FullName: "AngularWebApiSample.Models.UserDto",
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Class,
            Accessibility: MetadataAccessibility.Public,
            Properties: [],
            Attributes: [new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.GenerateFrontendTypeAttribute", Arguments: [])],
            BaseTypes: [],
            EnumValues: [],
            IsNullableAware: true);
        var createRequest = new TypeMetadata(
            Name: "CreateUserRequest",
            FullName: "AngularWebApiSample.Models.CreateUserRequest",
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Class,
            Accessibility: MetadataAccessibility.Public,
            Properties: [],
            Attributes: [new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.GenerateFrontendTypeAttribute", Arguments: [])],
            BaseTypes: [],
            EnumValues: [],
            IsNullableAware: true);

        return new ProjectMetadata(
            ProjectPath: "AngularWebApiSample.csproj",
            SourceFiles: [],
            Types: [controller, userDto, createRequest],
            Diagnostics: []);
    }

    private static ProjectMetadata CreateAngularWebApiModelMetadata()
    {
        const string CombinedFullName = "AngularWebApiSample.Models.CombinedQueryModel";
        const string SimpleModelFullName = "AngularWebApiSample.Models.SimpleModel";
        const string FirstSetFullName = "AngularWebApiSample.Models.FirstSet";
        const string SecondSetFullName = "AngularWebApiSample.Models.SecondSet";
        var simpleModelType = TypeReference(
            name: "SimpleModel",
            fullName: SimpleModelFullName,
            isNullable: false,
            isPrimitive: false);
        var firstSetType = TypeReference(
            name: "FirstSet",
            fullName: FirstSetFullName,
            isNullable: false,
            isPrimitive: false,
            isEnum: true);
        var secondSetType = TypeReference(
            name: "SecondSet",
            fullName: SecondSetFullName,
            isNullable: false,
            isPrimitive: false,
            isEnum: true);
        var simpleModelsType = TypeReference(
            name: "List",
            fullName: "System.Collections.Generic.List",
            isNullable: false,
            isPrimitive: false,
            isCollection: true,
            elementType: simpleModelType,
            typeArguments: [simpleModelType]);

        var combinedQueryModel = new TypeMetadata(
            Name: "CombinedQueryModel",
            FullName: CombinedFullName,
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Class,
            Accessibility: MetadataAccessibility.Public,
            Properties:
            [
                CreateProperty(parentFullName: CombinedFullName, name: "Id", type: TypeReference(name: "Int32", fullName: "System.Int32", isNullable: false)),
                CreateProperty(parentFullName: CombinedFullName, name: "SimpleModels", type: simpleModelsType),
                CreateProperty(parentFullName: CombinedFullName, name: "FirstName", type: TypeReference(name: "String", fullName: "System.String", isNullable: false)),
                CreateProperty(parentFullName: CombinedFullName, name: "MiddleName", type: TypeReference(name: "String", fullName: "System.String", isNullable: true)),
                CreateProperty(parentFullName: CombinedFullName, name: "LastName", type: TypeReference(name: "String", fullName: "System.String", isNullable: false)),
            ],
            Attributes: [new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.Attributes.GenerateFrontendTypeAttribute", Arguments: [])],
            BaseTypes: [],
            EnumValues: [],
            IsNullableAware: true)
        {
            AssemblyName = "AngularWebApiSample",
        };
        var simpleModel = new TypeMetadata(
            Name: "SimpleModel",
            FullName: SimpleModelFullName,
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Record,
            Accessibility: MetadataAccessibility.Public,
            Properties:
            [
                CreateProperty(parentFullName: SimpleModelFullName, name: "Num", type: TypeReference(name: "Int32", fullName: "System.Int32", isNullable: false)),
                CreateProperty(parentFullName: SimpleModelFullName, name: "Text", type: TypeReference(name: "String", fullName: "System.String", isNullable: true)),
                CreateProperty(parentFullName: SimpleModelFullName, name: "IsOk", type: TypeReference(name: "Boolean", fullName: "System.Boolean", isNullable: false)),
                CreateProperty(parentFullName: SimpleModelFullName, name: "FirstSet", type: firstSetType),
                CreateProperty(parentFullName: SimpleModelFullName, name: "SecondSet", type: secondSetType),
            ],
            Attributes: [new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.Attributes.GenerateFrontendTypeAttribute", Arguments: [])],
            BaseTypes: [],
            EnumValues: [],
            IsNullableAware: true)
        {
            AssemblyName = "AngularWebApiSample",
        };
        var firstSet = new TypeMetadata(
            Name: "FirstSet",
            FullName: FirstSetFullName,
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Enum,
            Accessibility: MetadataAccessibility.Public,
            Properties: [],
            Attributes: [new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.Attributes.GenerateFrontendTypeAttribute", Arguments: [])],
            BaseTypes: [],
            EnumValues:
            [
                CreateEnumValue(parentFullName: FirstSetFullName, name: "ValA", value: 0),
                CreateEnumValue(parentFullName: FirstSetFullName, name: "ValB", value: 1),
                CreateEnumValue(parentFullName: FirstSetFullName, name: "SomeOtherVal", value: 2),
            ],
            IsNullableAware: true)
        {
            AssemblyName = "AngularWebApiSample",
        };
        var secondSet = new TypeMetadata(
            Name: "SecondSet",
            FullName: SecondSetFullName,
            Namespace: "AngularWebApiSample.Models",
            Kind: TypeMetadataKind.Enum,
            Accessibility: MetadataAccessibility.Public,
            Properties: [],
            Attributes:
            [
                new AttributeMetadata(Name: "AsString", FullName: "AngularWebApiSample.Attributes.AsStringAttribute", Arguments: []),
                new AttributeMetadata(Name: "GenerateFrontendType", FullName: "AngularWebApiSample.Attributes.GenerateFrontendTypeAttribute", Arguments: []),
            ],
            BaseTypes: [],
            EnumValues:
            [
                CreateEnumValue(parentFullName: SecondSetFullName, name: "ValA", value: 0),
                CreateEnumValue(parentFullName: SecondSetFullName, name: "ValB", value: 1),
                CreateEnumValue(parentFullName: SecondSetFullName, name: "SomeOtherVal", value: 2),
            ],
            IsNullableAware: true)
        {
            AssemblyName = "AngularWebApiSample",
        };

        return new ProjectMetadata(
            ProjectPath: "AngularWebApiSample.csproj",
            SourceFiles: [],
            Types: [combinedQueryModel, simpleModel, firstSet, secondSet],
            Diagnostics: []);
    }

    private static EnumValueMetadata CreateEnumValue(
        string parentFullName,
        string name,
        long value)
    {
        return new EnumValueMetadata(Name: name, Value: value)
        {
            ParentTypeFullName = parentFullName,
        };
    }

    private static PropertyMetadata CreateProperty(
        string parentFullName,
        string name,
        TypeMetadataReference type)
    {
        return new PropertyMetadata(
            Name: name,
            FullName: parentFullName + "." + name,
            Type: type,
            Accessibility: MetadataAccessibility.Public,
            HasGetter: true,
            HasSetter: true,
            IsRequired: false,
            Attributes: [])
        {
            ParentTypeFullName = parentFullName,
        };
    }

    private static TypeMetadataReference TypeReference(
        string name,
        string fullName,
        bool isNullable,
        bool? isPrimitive = null,
        bool isCollection = false,
        bool isDictionary = false,
        bool isEnum = false,
        bool isDateLike = false,
        TypeMetadataReference? elementType = null,
        IReadOnlyList<TypeMetadataReference>? typeArguments = null)
    {
        return new TypeMetadataReference(
            Name: name,
            FullName: fullName,
            Namespace: GetNamespace(fullName: fullName),
            IsNullable: isNullable,
            IsCollection: isCollection,
            IsDictionary: isDictionary,
            IsEnum: isEnum,
            IsPrimitive: isPrimitive ?? IsPrimitive(fullName: fullName),
            IsDateLike: isDateLike,
            ElementType: elementType,
            TypeArguments: typeArguments ?? []);
    }

    private static string GetNamespace(string fullName)
    {
        var index = fullName.LastIndexOf(value: '.');
        return index < 0 ? string.Empty : fullName[..index];
    }

    private static bool IsPrimitive(string fullName)
    {
        return fullName is "System.Boolean"
            or "System.Byte"
            or "System.SByte"
            or "System.Int16"
            or "System.UInt16"
            or "System.Int32"
            or "System.UInt32"
            or "System.Int64"
            or "System.UInt64"
            or "System.Single"
            or "System.Double"
            or "System.Decimal"
            or "System.String"
            or "System.Char";
    }
}
